### ISSUE TITLE
Nefunkční zobrazování průměru známek

### ISSUE THREAD

**Issue by Sosto1** [jakubhyza/skola-online-prumer-znamek#2]
Nezobrazuje průměry 
![image](https://user-images.githubusercontent.com/90568906/207883575-3e0e0760-624e-486f-8e4c-34344f19055d.png)
Celkový průměr také nejede
![image](https://user-images.githubusercontent.com/90568906/207883758-8b46428d-8df4-4601-b008-158f29dc4350.png)

**Comment by sarahyzova** [comment]
Omlouvám se, dneska vyšla aktualizace a pravděpodobně se něco porouchalo.
Můžete prosím podívat do konzole jestli se nezobrazuje nějaké chyba případně kdyby jste mi poslal přehled celý přehled vašich známek abych mohlo lépe porozumět s čím má plugin přesně problém. (pokud nechcete veřejně, můžete mi ho taktéž poslat na email info@jakubhyza.cz)

**Comment by sarahyzova** [comment]
Byla vydána nová verze. Je problém opraven, nebo stále přetrvává?

**Comment by Sosto1** [comment]
Problém byl opraven, vše se zobrazuje jak má.
