### ISSUE TITLE
Na některých předmětech neukazuje průměry

### ISSUE THREAD

**Issue by venca843** [jakubhyza/skola-online-prumer-znamek#4]
![image](https://user-images.githubusercontent.com/122471450/211862880-b8aaedfe-a7d4-4922-9d95-a6858763ca25.png)
![image](https://user-images.githubusercontent.com/122471450/211862940-b3b551a6-fc30-4012-b4c2-71fc4781e27c.png)
Vždy fungovalo, ale poslední dobou po přidávání známek ukazuje u některých předmětů tohle.

**Comment by sarahyzova** [comment]
Děkuji Vám za nahlášení chyby.
K vyhodnocení problému bych potřeboval screenshot se všemi známkami. Potřebuji zjistit co přesně způsobuje, že výpočet pro daný řádek selže. Pokud se vám nechce posílat svoje známky veřejně, můžete mi taktéž napsat e-mail na `info@jakubhyza.cz`.

**Comment by venca843** [comment]
Pošlu na e-mail.

**Comment by sarahyzova** [comment]
Mělo by to být opraveno. Aktualizujte plugin a otestujte prosím.

**Comment by venca843** [comment]
Všechno už nyní funguje. Děkuji za rychlou reakci a za rychlé opravení chyby. Mohl bych se jen tak pro zajímavost zeptat, proč se to dělo jenom u některých předmětů?

**Comment by sarahyzova** [comment]
Dělo se to pouze u předmětů, ve kterých bylo nějaké slovní hodnocení a plugin nevěděl, jak s takovým hodnocením počítat.
